### PR TITLE
Add Python 3.6 builds

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Comment by cpcloud** [comment]
@mariusvniekerk Can you review and merge this when you get a chance? I'm trying to cut the 0.12.0 release of ibis including Python 3.6 builds and this package is blocking.

**Comment by cpcloud** [comment]
cc @ericdill @parente

**Comment by cpcloud** [comment]
ping @conda-forge/python-hdfs

**Comment by ericdill** [comment]
Hi @cpcloud -- The recipe is still skipping python 3.6. You'll need to delete [this line](https://github.com/conda-forge/python-hdfs-feedstock/blob/master/recipe/meta.yaml#L13) and then rerender with the latest conda-smithy after deleting that line.  A pressing issue here is *why was py36 skipped in the first place?* I'll go do some digging on staged-recipes and see if I can figure that out.

**Comment by ericdill** [comment]
Alright looks like @parente added the skip for python 3.6 [due to some incompatible dependencies](https://github.com/conda-forge/python-hdfs-feedstock/pull/5) which I think have all been updated to be python 3.6. I suspect this will build py3.6 packages just fine after you remove the offending line in the meta.yaml and rerender with conda-smithy. I can also take over if you'd like. Just let me know

**Comment by ericdill** [comment]
lgtm thanks @cpcloud

**Pull request merged**
